//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lingoine1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LeapNullEntities : DbContext
    {
        public LeapNullEntities()
            : base("name=LeapNullEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LanguageTable> LanguageTables { get; set; }
        public virtual DbSet<UserLanguageTable> UserLanguageTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    
        public virtual int Normal_UserAssign(string learnerEmail, string lName, ObjectParameter nTeacherSkype)
        {
            var learnerEmailParameter = learnerEmail != null ?
                new ObjectParameter("LearnerEmail", learnerEmail) :
                new ObjectParameter("LearnerEmail", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Normal_UserAssign", learnerEmailParameter, lNameParameter, nTeacherSkype);
        }
    
        public virtual int sp_AssignTeacher(string learnerEmail, string lName, ObjectParameter teacherSkype)
        {
            var learnerEmailParameter = learnerEmail != null ?
                new ObjectParameter("LearnerEmail", learnerEmail) :
                new ObjectParameter("LearnerEmail", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AssignTeacher", learnerEmailParameter, lNameParameter, teacherSkype);
        }
    
        public virtual int sp_authenticate(string uEmail, string uPassword, ObjectParameter result)
        {
            var uEmailParameter = uEmail != null ?
                new ObjectParameter("UEmail", uEmail) :
                new ObjectParameter("UEmail", typeof(string));
    
            var uPasswordParameter = uPassword != null ?
                new ObjectParameter("UPassword", uPassword) :
                new ObjectParameter("UPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_authenticate", uEmailParameter, uPasswordParameter, result);
        }
    
        public virtual int sp_EndCall(string teacherEmail, string learnerEmail, string lName, Nullable<double> uRating)
        {
            var teacherEmailParameter = teacherEmail != null ?
                new ObjectParameter("TeacherEmail", teacherEmail) :
                new ObjectParameter("TeacherEmail", typeof(string));
    
            var learnerEmailParameter = learnerEmail != null ?
                new ObjectParameter("LearnerEmail", learnerEmail) :
                new ObjectParameter("LearnerEmail", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            var uRatingParameter = uRating.HasValue ?
                new ObjectParameter("URating", uRating) :
                new ObjectParameter("URating", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EndCall", teacherEmailParameter, learnerEmailParameter, lNameParameter, uRatingParameter);
        }
    
        public virtual int sp_SignIn(string uEmail)
        {
            var uEmailParameter = uEmail != null ?
                new ObjectParameter("UEmail", uEmail) :
                new ObjectParameter("UEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SignIn", uEmailParameter);
        }
    
        public virtual int sp_SignOut(string uEmail)
        {
            var uEmailParameter = uEmail != null ?
                new ObjectParameter("UEmail", uEmail) :
                new ObjectParameter("UEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SignOut", uEmailParameter);
        }
    
        public virtual int sp_StartCall(string teacherEmail, string learnerEmail, string languageName)
        {
            var teacherEmailParameter = teacherEmail != null ?
                new ObjectParameter("TeacherEmail", teacherEmail) :
                new ObjectParameter("TeacherEmail", typeof(string));
    
            var learnerEmailParameter = learnerEmail != null ?
                new ObjectParameter("LearnerEmail", learnerEmail) :
                new ObjectParameter("LearnerEmail", typeof(string));
    
            var languageNameParameter = languageName != null ?
                new ObjectParameter("LanguageName", languageName) :
                new ObjectParameter("LanguageName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_StartCall", teacherEmailParameter, learnerEmailParameter, languageNameParameter);
        }
    }
}
